#!/system/bin/sh

bindir="$(dirname "$(realpath "$0")")"
execname="$(basename "$0")"

if [ "$USER" == "root" -o "$(whoami 2>/dev/null)" == "root" ]; then
  exec env LD_LIBRARY_PATH="$(realpath "$bindir/../../lib")" "$bindir/$execname" "$@"
else
  echo "$execname: need root permissions"
fi
